# .github/release.yml

changelog:
  categories:
    - title: Exciting New Features 🎉
      labels:
        - "Type: Feature"
    - title: Improvements 🚀
      labels:
        - "Type: Refactor"
    - title: Bug Fixes 🐞
      labels:
        - "Type: Fix"
    - title: House Keeping 🏠
      labels:
        - "Type: House Keeping"
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Dependencies 🆙
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
